apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost-on-kubernetes.fullname" . | trunc 8 | trimSuffix "-" }}-svc
  labels:
    app: {{ include "ghost-on-kubernetes.fullname" . }}-ghost
  {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "ghost-on-kubernetes.fullname" . }}-ghost
  {{- include "ghost-on-kubernetes.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.ghostConfigProd.port }}
      protocol: TCP
      targetPort: 2368
      name: {{ include "ghost-on-kubernetes.fullname" . | trunc 8 | trimSuffix "-" }}-svc

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost-on-kubernetes.fullname" . }}-mysql
  labels:
    app: {{ include "ghost-on-kubernetes.fullname" . }}-mysql
  {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "ghost-on-kubernetes.fullname" . }}-mysql
  ports:
    - port: {{ .Values.mysqlGhostOnKubernetes.mysqlPort }}
      protocol: TCP
      targetPort: {{ .Values.mysqlGhostOnKubernetes.mysqlPort }}
      name: mysql
  clusterIP: None
  
  

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost-on-kubernetes
  labels:
  {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.ingressHost }} 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "ghost-on-kubernetes.fullname" . | trunc 8 | trimSuffix "-" }}-svc
            port:
              number: {{ .Values.ghostConfigProd.port }}

# Add tls config if tlsSecretName is not empty, else do nothing       
{{- if .Values.tlsSecretName }}
  tls:
  - hosts:
    - {{ .Values.ingressHost }}
    secretName: {{ .Values.tlsSecretName }}
{{- end }}
