{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost-on-kubernetes.fullname" . }}-mysql-env
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "ghost-on-kubernetes.name" . }}-mysql
    {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}
    app.kubernetes.io/component: database-secret
type: Opaque
stringData:
  MYSQL_DATABASE: {{ .Values.mysql.auth.database | quote }}
  MYSQL_USER: {{ .Values.mysql.auth.username | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.auth.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | quote }}
  MYSQL_HOST: '%'
{{- end }}
