apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost-on-kubernetes.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}
    app.kubernetes.io/component: service-frontend
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: ghk8s
    name: ghk8s
  type: {{ .Values.service.type }}
  selector:
    {{- include "ghost-on-kubernetes.selectorLabels" . | nindent 4 }}
---
{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost-on-kubernetes.fullname" . }}-mysql-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "ghost-on-kubernetes.name" . }}-mysql
    {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}
    app.kubernetes.io/component: service-database
spec:
  ports:
  - port: {{ .Values.service.mysql.port }}
    protocol: TCP
    targetPort: mysqlgh
    name: mysqlgh
  type: {{ .Values.service.mysql.type }}
  clusterIP: None
  selector:
    app: {{ include "ghost-on-kubernetes.name" . }}-mysql
{{- end }}
