apiVersion: v1
kind: Secret
metadata:
  name: ghost-config-prod
  namespace: ghost-on-kubernetes
  labels:
    app: ghost-on-kubernetes
    app.kubernetes.io/name: ghost-config-prod
    app.kubernetes.io/instance: ghost-on-kubernetes
    app.kubernetes.io/version: '5.92'
    app.kubernetes.io/component: ghost-config
    app.kubernetes.io/part-of: ghost-on-kubernetes
type: Opaque
stringData:
  config.production.json: |-
    {
      "url": "https://yourdomain.tld",
      "admin": {
        "url": "https://yourdomain.tld"
      },
      "server": {
        "port": 2368,
        "host": "0.0.0.0"
      },
      "mail": {
        "transport": "SMTP",
        "from": "user@server.com",
        "options": {
          "service": "Google",
          "host": "smtp.gmail.com",
          "port": 465,
          "secure": true,
          "auth": {
            "user": "user@server.com",
            "pass": "passsword"
          }
        }
      },
      "logging": {
        "transports": [
          "stdout"
        ]
      },
      "database": {
        "client": "mysql",
        "connection": 
        {
          "host": "ghost-on-kubernetes-mysql-service",
          "user": "mysql-db-user",
          "password": "mysql-db-password",
          "database": "mysql-db-name",
          "port": "3306"
        }
      },
      "process": "local",
      "paths": {
        "contentPath": "/home/nonroot/app/ghost/content"
      }
    }
