apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost-k8s
  namespace: ghost-k8s
spec:
  ingressClassName: traefik # or nginx, caddy, etc
  tls:
  - hosts:
    - tests.yourdomain.com
    # Optional:
    # - www.tests.yourdomain.com
    secretName: yourdomain-com-tls
  rules:
  - host: tests.yourdomain.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: ghost-k8s-svc
            port:
              name: ghk3s
  # Optional:
  # - host: www.tests.yourdomain.com
  #   http:
  #     paths:
  #     - path: /
  #       pathType: ImplementationSpecific
  #       backend:
  #         service:
  #           name: ghost-k8s-svc
  #           port:
  #             name: ghk3s


