# Chart.yaml
apiVersion: v2
name: ghost-on-kubernetes
description: A Helm chart for deploying Ghost CMS v6 on Kubernetes with enhanced security
type: application
version: 1.0.0
appVersion: "6.0"
keywords:
  - ghost
  - cms
  - blog
  - publishing
home: https://github.com/sredevopsorg/ghost-on-kubernetes
sources:
  - https://github.com/sredevopsorg/ghost-on-kubernetes
maintainers:
  - name: SREDevOps.org
    url: https://www.sredevops.org
icon: "https://www.sredevops.org/content/images/size/w256h256/2024/07/Icon-App-76x76@2x.png"
