name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - "Charts/**"
      - .github/workflows/helm-release.yaml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'ngeorger' }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        id: install
        with:
          version: latest


      - name: Run chart-releaser (old)
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        with:
          charts_dir: Charts
          pages_branch: gh-pages
          mark_as_latest: false
          skip_existing: true
          packages_with_index: true
          # version:
          # config:
          # skip_packaging:
          # skip_upload:
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser (New)
        uses: sredevopsorg/helm-oci-charts-releaser@v0.0.1
        continue-on-error: true
        with:
            oci_registry: ghcr.io/sredevopsorg
            oci_username: ${{ github.actor }}
            oci_password: ${{ secrets.GITHUB_TOKEN }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
            charts_dir: Charts
            skip_helm_install: true
            skip_existing: true
            mark_as_latest: false
            skip_gh_release: true
            oci_tag_pattern: "{chartName}-{version}"
            # tag_name_pattern: "{chartName}-chart"
